name: Scraping API Noticias

on:
  push:
    branches:
      - master  # Cambia esto si usas una rama diferente
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: jafr0691
          password: Juan..0619

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: jafr0691/scraping_noticias_cristianas:latest
