name: Scraping API Noticias

on:
  push:
    branches:
      - master  # Cambia esto si usas una rama diferente
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest  # Cambiado para usar el entorno correcto

    steps:
      # Paso 1: Checkout del código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3  # Actualización a la versión más reciente

      # Paso 2: Iniciar sesión en Docker Hub usando secretos de GitHub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: jafr0691  # Usa secretos de GitHub para el nombre de usuario
          password: Juan..0619  # Usa secretos de GitHub para la contraseña

      # Paso 3: Construir y subir la imagen de Docker a Docker Hub
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64  # Especificar la plataforma correcta
          push: true
          tags: jafr0691/scraping_noticias_cristianas:latest  # Etiqueta para la imagen en Docker Hub
