name: Scraping API Noticias

on:
  push:
    branches:
      - master  # Cambia esto si usas una rama diferente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ DOCKER_USERNAME.DOCKER_USERNAME }}
          password: ${{ DOCKER_USERNAME.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: jafr0691/scraping_noticias_cristianas:latest  # Cambia esto con tu usuario de Docker Hub y el nombre de la imagen
