name: Scraping API Noticias

on:
  push:
    branches:
      - master  # Cambia esto si usas una rama diferente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: your-dockerhub-username/your-image-name:latest  # Cambia esto con tu usuario de Docker Hub y el nombre de la imagen

      - name: Deploy to a cloud service
        run: |
          # Aquí puedes agregar comandos para desplegar tu contenedor, por ejemplo en Heroku, AWS, DigitalOcean, etc.
