name: Scraping API Noticias

on:
  push:
    branches:
      - master  # Cambia esto si usas una rama diferente
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t jafr0691/scraping_noticias_cristianas:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push jafr0691/scraping_noticias_cristianas:latest
