name: scraping api noticias

on:  # Eliminar disparadores push y pull_request
  workflow_dispatch:  # Permite ejecutar el flujo manualmente desde GitHub si lo deseas

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest selenium webdriver-manager flask gunicorn

    - name: Install Firefox and Geckodriver
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox
        wget https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz
        tar -xvzf geckodriver-v0.33.0-linux64.tar.gz
        sudo mv geckodriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/geckodriver

    - name: Check Geckodriver Version
      run: |
        geckodriver --version

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Start the Flask app
      run: |
        nohup gunicorn --bind 0.0.0.0:8080 noticias_cristianas:app &  # Ejecuta el servidor en segundo plano

    - name: Wait for the server to start
      run: |
        sleep 10  # Esperar a que el servidor esté listo

    - name: Test the API with curl
      run: |
        curl http://localhost:8080/testimonio-del-dia  # Realiza una consulta a la API para verificar que está funcionando
